//List with digimon to skip, they don't have a type and made the card aestethic look bad
//but in the api to check for type it would check all 1488 digimon individually to find
//the ones without type, which sounded like a big resource hog, and since there weren't
//that many of them I found it easier to do it manually, ideally the api would be better
//suited for this

export const filterSkip = (content) => {
  return content?.filter(digimon => !skipDigimon.has(digimon.name)) ?? []
}

export const skipPattern = ['(2006 Anime Version)']

export const skipDigimon = new Set([
  "Death Airdramon", 
  "Death Devimon", 
  "Death Meramon (C'mon Digimon Version)", 
  "Death Metal Greymon", 
  "Death Tyranomon",
  "Deathmon (C'mon Digimon Version)",
  "Ohakadamon",
  "Fujitsumon",
  "Golemon (PS)",
  "Chaos Greymon",
  "Chaos Seadramon",
  "Chaos Lord",
  "Technodramon",
  "Generamon",
  "Holy Digitamamon",
  "Negamon (Evolved Form)",
  "Jyureimon (Christmas Tree)",
  "Woodwoodymon",
  "Bancho Golemon",
  "Kuzuhamonchiko Mode",
  "Sistermon Noir (Awake)",
  "Sistermon Blanc (Awake",
  "Xros Up Arresterdramon (Orgemon)",
  "Xros Up Astamon (Cerberumon)",
  "Xros Up Opossummon (Candmon)",
  "Xros Up Arresterdramon (Astamon)",
  "Jiko Tyumon",
  "Cardmon C1",
  "Cardmon C2",
  "Cardmon R1",
  "Cardmon S1",
  "Cardmon S2",
  "Cardmon U1",
  "Cardmon U2",
  "Gallantmon Chaos Mode",
  "Lykamon",
  "Bun",
  "Blikmon",
  "Kohagurumon",
  "Greymon (Skull Knightmon)",
  "Trailmon Angler",
  "Trailmon Buffalo",
  "Trailmon Franken",
  "Trailmon Mole",
  "Trailmon Raccoon Dog",
  "Trailmon of Darkness",
  "Battle Armament Trailmon",
  "Dot Gaomon",
  "Trailmon Battle Form",
  "Bancho Leomon(Burst Mode)",
  "Agumon(Burst Mode)",
  "Citramon",
  "Ballistamon SR",
  "Ballistamon MC",
  "Chibick Sword",
  "Beelzebumon (Starmons)",
  "Mail Birdramon (Golemon)",
  "Mega Dark Knightmon",
  "Mega Gran Kuwagamon",
  "Mush-Upped Mach Leomon",
  "Ochi Musyamon",
  "Star Axe",
  "Rare Star Sword",
  "Reverse Weddinmon",
  "Sakuteki Monitamon",
  "Scud Missimon",
  "Shoutmon SH",
  "Shoutmon (Blue)",
  "Shoutmon B",
  "Shoutmon X4S",
  "Shoutmon X2 (Incomplete X4)",
  "Shoutmon X5 (Skull Greymon)",
  "Hi Mugendramon",
  "Aircraft Carrier Whamon",
  "Beelzebumon (Revolmon)",
  "Dark Knightmon (Blastmon)",
  "Dark Knightmon (Duskmon)",
  "Dark Knightmon (Gulfmon)",
  "Dark Knightmon (Lilithmon)",
  "Deckerdramon Float Mode",
  "Dorbickmon Darkness Mode (Flare Lizamon)",
  "Mega Black Shoutmon X7",
  "Mega Darkness Bagramon",
  "Mega Decker Greymon",
  "Mega Muso Knightmon",
  "Neo Vamdemon Darkness Mode (Shoutmon)",
  "Omega Armamon Burst Mode",
  "Sparrowmon AB",
  "Shoutmon X6",
  "Shoutmon X7(Superior Mode)",
  "Bagramon (Archangel Form)",
  "Skull Knightmon (White)",
  "Greymon (Skull Knightmon)",
  "Neo Vamdemon Darkness Mode (Shoutmon)",
  "Gallantmon Chaos Mode",
  ""
])